### ISSUE TITLE
sigma_dev is never created in HMM

### ISSUE THREAD

**Issue by jlgreathouse** [NUCAR-DEV/Hetero-Mark#48]
For both the OpenCL 1.2 and OpenCL 2.0 versions of HMM, the buffer `sigma_dev` is never created.

For the OpenCL 2.0 version, this means that you are passing a NULL pointer into `clSetKernelArgSVMPointer()` for multiple kernels. In the current AMD OpenCL runtime, this causes the `clSetKernelArgSVMPointer()` to return `CL_SUCCESS`, but the kernel later fails to actually run. If you attempt to profile this kernel, you will see that `clGetEventProfilingInfo(CL_PROFILING_COMMAND_START)` or `clGetEventProfilingInfo(CL_PROFILING_COMMAND_END)` will return `CL_PROFILING_INFO_NOT_AVAILABLE`.

I haven't deeply looked into what this does for OpenCL 1.2, but suffice it to say, this is an error.

**Comment by syifan** [comment]
Hi @jlgreathouse 

Thank you very much for your contribute. Sorry for not being able to show that on Github, we have moved to another code base temporarily due to the file size limitation of GitHub. Therefore, some of your problems may have already been solved in our planned next release.  But some of your points is still valid to us. We will not merge in your pull requests for now. But we will check our newer version and see if the problems are still there. And we can integrate your update in our new release. Does that sound good?

I have made our most recent code available in the branch release-2.0a2. So if you need, please feel free to download it there. We have moved the standard data file in another file server. So, we can come back to Github.  

Thanks again for your contribution. We appreciate any form of feedback. 

Yifan

**Comment by jlgreathouse** [comment]
Hello @sunyifan112358 

It would be nice if these changes were still merged into the current release (perhaps as a 1.0 point release), even if Hetero-Mark 2.0 will have some of them fixed. For now, people downloading from the default develop branch will get somewhat broken benchmarks. For me, either way works; I have a branch of your repo that has all of my my PRs (and more), so I do not have problems running things anymore.

Looking through release-2.0a2, it looks like the, issue #40 still needs to be fixed by PR #41.

These problems no longer exist:
- The sw problem (#39) doesn't exist anymore, since the benchmark has been removed.
- The SVM memory leak in kmeans (#42) no longer exists.
- The kmeans unmap problem (#43) is solved, since you have moved to using fine-grained SVM and have no maps or unamps.
  - As an aisde, I would wager this would perform somewhat poorly, as fine-grained SVM buffers are currently mapped into host memory, on the other side of the PCIe bus, on AMD dGPUs).
- The question about IIR (#46) no longer holds, as that benchmark has been removed.
- The problem in this issue (#48) no longer exists, as HMM has been removed.

**Comment by syifan** [comment]
@jlgreathouse Thanks a lot. I will merge them. In the new release, I will manually update since the code has been changed a lot.

We removed some benchmarks to make the 2.0 release match our IISWC paper. But we will add them back later after the release. So your suggestion is still very helpful.

For KMeans, I think it would be interesting to examine coarse-grained SVM vs fine-grained SVM. We will evaluate and solve this problem in 2.0 release.

Adding @xianggong @saonim in this thread.
